ALTER TABLE products
  ADD COLUMN full_description TEXT NULL AFTER description;

ALTER TABLE product_types
  ADD COLUMN meta_title VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_description VARCHAR(255) DEFAULT NULL,
  ADD COLUMN meta_keywords VARCHAR(255) DEFAULT NULL,
  ADD COLUMN h1 VARCHAR(255) DEFAULT NULL,
  ADD COLUMN short_description TEXT DEFAULT NULL,
  ADD COLUMN text TEXT DEFAULT NULL;
