CREATE TABLE sitemap_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    is_active TINYINT(1) NOT NULL DEFAULT 0,
    last_generated DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE materials
  ADD COLUMN in_sitemap TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE products
  ADD COLUMN in_sitemap TINYINT(1) NOT NULL DEFAULT 1;
