CREATE TABLE IF NOT EXISTS production_jobs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id INT UNSIGNED NOT NULL,
  product_id INT UNSIGNED DEFAULT NULL,
  executor_type ENUM('internal_staff','production_partner','marketplace_seller','brand_partner') DEFAULT NULL,
  executor_id INT UNSIGNED DEFAULT NULL,
  fulfillment_model ENUM('by_berrygo_on_site','by_berrygo_remote','by_partner_under_berrygo_brand','by_seller','by_berrygo_from_seller_stock') NOT NULL DEFAULT 'by_berrygo_on_site',
  production_location ENUM('shop','remote','partner','seller') NOT NULL DEFAULT 'shop',
  status ENUM('new','assigned','materials_pending','materials_sent','materials_received','in_progress','photo_uploaded','approved','ready_for_handover','handed_over','completed','cancelled','problem') NOT NULL DEFAULT 'new',
  production_deadline DATETIME DEFAULT NULL,
  handover_deadline DATETIME DEFAULT NULL,
  bonus_type ENUM('salary','internal_bonus','fixed_payout','commission','subscription','commission_plus_subscription','fixed_fee_per_order') NOT NULL DEFAULT 'internal_bonus',
  bonus_value DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  bonus_amount_locked DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  materials_required JSON DEFAULT NULL,
  materials_delivery_required TINYINT(1) NOT NULL DEFAULT 0,
  materials_delivery_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  result_delivery_required TINYINT(1) NOT NULL DEFAULT 0,
  result_delivery_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  manager_comment TEXT DEFAULT NULL,
  assigned_at DATETIME DEFAULT NULL,
  started_at DATETIME DEFAULT NULL,
  photo_uploaded_at DATETIME DEFAULT NULL,
  approved_at DATETIME DEFAULT NULL,
  handed_over_at DATETIME DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_production_jobs_order_id (order_id),
  KEY idx_production_jobs_status_deadline (status, production_deadline),
  KEY idx_production_jobs_executor_status (executor_type, executor_id, status),
  KEY idx_production_jobs_fulfillment_status (fulfillment_model, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS production_job_events (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id INT UNSIGNED NOT NULL,
  order_id INT UNSIGNED NOT NULL,
  from_status VARCHAR(32) DEFAULT NULL,
  to_status VARCHAR(32) NOT NULL,
  changed_by_user_id INT UNSIGNED DEFAULT NULL,
  changed_by_role VARCHAR(32) DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_production_job_events_job_id (job_id),
  KEY idx_production_job_events_order_id (order_id),
  KEY idx_production_job_events_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
