CREATE TABLE IF NOT EXISTS `purchase_batches` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` int UNSIGNED NOT NULL,
  `buyer_user_id` int UNSIGNED DEFAULT NULL,
  `purchased_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `arrived_at` datetime DEFAULT NULL,
  `box_size_snapshot` decimal(10,2) NOT NULL DEFAULT 0,
  `box_unit_snapshot` enum('кг','л') NOT NULL DEFAULT 'кг',
  `boxes_total` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_reserved` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_free` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_sold` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_discount` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_written_off` decimal(10,2) NOT NULL DEFAULT 0,
  `boxes_remaining` decimal(10,2) NOT NULL DEFAULT 0,
  `purchase_price_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `extra_cost_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `cost_price_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `preorder_margin_percent` decimal(5,2) NOT NULL DEFAULT 30.00,
  `instant_margin_percent` decimal(5,2) NOT NULL DEFAULT 50.00,
  `discount_markup_fixed` decimal(10,2) NOT NULL DEFAULT 100.00,
  `preorder_price_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `instant_price_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `discount_price_per_box` decimal(10,2) NOT NULL DEFAULT 0,
  `preorder_unit_price` decimal(10,2) NOT NULL DEFAULT 0,
  `instant_unit_price` decimal(10,2) NOT NULL DEFAULT 0,
  `discount_unit_price` decimal(10,2) NOT NULL DEFAULT 0,
  `status` enum('planned','purchased','arrived','active','sold_out','closed','cancelled') NOT NULL DEFAULT 'purchased',
  `comment` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_purchase_batches_product` (`product_id`),
  KEY `idx_purchase_batches_buyer` (`buyer_user_id`),
  KEY `idx_purchase_batches_status` (`status`),
  KEY `idx_purchase_batches_purchased_at` (`purchased_at`),
  CONSTRAINT `fk_purchase_batches_product`
    FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_purchase_batches_buyer`
    FOREIGN KEY (`buyer_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
